name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Проверим, что установка прошла успешно

      - name: Build video_processor image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./video_processor/Dockerfile
          push: false
          tags: video_processor:latest

      - name: Build video_searcher image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./video_searcher/Dockerfile
          push: false
          tags: video_searcher:latest

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec video_processor pytest tests/
          docker-compose exec video_searcher pytest tests/
